all:
  planner_configs:
  - SBLkConfigDefault
  - ESTkConfigDefault
  - LBKPIECEkConfigDefault
  - BKPIECEkConfigDefault
  - KPIECEkConfigDefault
  - RRTkConfigDefault
  - RRTConnectkConfigDefault
  - RRTstarkConfigDefault
  - TRRTkConfigDefault
  - PRMkConfigDefault
  - PRMstarkConfigDefault
  - FMTkConfigDefault
  - BFMTkConfigDefault
  - PDSTkConfigDefault
  - STRIDEkConfigDefault
  - BiTRRTkConfigDefault
  - LBTRRTkConfigDefault
  - BiESTkConfigDefault
  - ProjESTkConfigDefault
  - LazyPRMkConfigDefault
  - LazyPRMstarkConfigDefault
  - SPARSkConfigDefault
  - SPARStwokConfigDefault
planner_configs:
  BFMTkConfigDefault:
    balanced: 0
    cache_cc: 1
    extended_fmt: 1
    heuristics: 1
    nearest_k: 1
    num_samples: 1000
    optimality: 1
    radius_multiplier: 1.0
    type: geometric::BFMT
  BKPIECEkConfigDefault:
    border_fraction: 0.9
    failed_expansion_score_factor: 0.5
    min_valid_path_fraction: 0.5
    range: 0.0
    type: geometric::BKPIECE
  BiESTkConfigDefault:
    range: 0.0
    type: geometric::BiEST
  BiTRRTkConfigDefault:
    cost_threshold: 1e300
    frountier_node_ratio: 0.1
    frountier_threshold: 0.0
    init_temperature: 100
    range: 0.0
    temp_change_factor: 0.1
    type: geometric::BiTRRT
  ESTkConfigDefault:
    goal_bias: 0.05
    range: 0.0
    type: geometric::EST
  FMTkConfigDefault:
    cache_cc: 1
    extended_fmt: 1
    heuristics: 0
    nearest_k: 1
    num_samples: 1000
    radius_multiplier: 1.1
    type: geometric::FMT
  KPIECEkConfigDefault:
    border_fraction: 0.9
    failed_expansion_score_factor: 0.5
    goal_bias: 0.05
    min_valid_path_fraction: 0.5
    range: 0.0
    type: geometric::KPIECE
  LBKPIECEkConfigDefault:
    border_fraction: 0.9
    min_valid_path_fraction: 0.5
    range: 0.0
    type: geometric::LBKPIECE
  LBTRRTkConfigDefault:
    epsilon: 0.4
    goal_bias: 0.05
    range: 0.0
    type: geometric::LBTRRT
  LazyPRMkConfigDefault:
    range: 0.0
    type: geometric::LazyPRM
  LazyPRMstarkConfigDefault:
    type: geometric::LazyPRMstar
  PDSTkConfigDefault:
    type: geometric::PDST
  PRMkConfigDefault:
    max_nearest_neighbors: 10
    type: geometric::PRM
  PRMstarkConfigDefault:
    type: geometric::PRMstar
  ProjESTkConfigDefault:
    goal_bias: 0.05
    range: 0.0
    type: geometric::ProjEST
  RRTConnectkConfigDefault:
    range: 0.0
    type: geometric::RRTConnect
  RRTkConfigDefault:
    goal_bias: 0.05
    range: 0.0
    type: geometric::RRT
  RRTstarkConfigDefault:
    delay_collision_checking: 1
    goal_bias: 0.05
    range: 0.0
    type: geometric::RRTstar
  SBLkConfigDefault:
    range: 0.0
    type: geometric::SBL
  SPARSkConfigDefault:
    dense_delta_fraction: 0.001
    max_failures: 1000
    sparse_delta_fraction: 0.25
    stretch_factor: 3.0
    type: geometric::SPARS
  SPARStwokConfigDefault:
    dense_delta_fraction: 0.001
    max_failures: 5000
    sparse_delta_fraction: 0.25
    stretch_factor: 3.0
    type: geometric::SPARStwo
  STRIDEkConfigDefault:
    degree: 16
    estimated_dimension: 0.0
    goal_bias: 0.05
    max_degree: 18
    max_pts_per_leaf: 6
    min_degree: 12
    min_valid_path_fraction: 0.2
    range: 0.0
    type: geometric::STRIDE
    use_projected_distance: 0
  TRRTkConfigDefault:
    frountierNodeRatio: 0.1
    frountier_threshold: 0.0
    goal_bias: 0.05
    init_temperature: 10e-6
    k_constant: 0.0
    max_states_failed: 10
    min_temperature: 10e-10
    range: 0.0
    temp_change_factor: 2.0
    type: geometric::TRRT
r0:
  planner_configs:
  - SBLkConfigDefault
  - ESTkConfigDefault
  - LBKPIECEkConfigDefault
  - BKPIECEkConfigDefault
  - KPIECEkConfigDefault
  - RRTkConfigDefault
  - RRTConnectkConfigDefault
  - RRTstarkConfigDefault
  - TRRTkConfigDefault
  - PRMkConfigDefault
  - PRMstarkConfigDefault
  - FMTkConfigDefault
  - BFMTkConfigDefault
  - PDSTkConfigDefault
  - STRIDEkConfigDefault
  - BiTRRTkConfigDefault
  - LBTRRTkConfigDefault
  - BiESTkConfigDefault
  - ProjESTkConfigDefault
  - LazyPRMkConfigDefault
  - LazyPRMstarkConfigDefault
  - SPARSkConfigDefault
  - SPARStwokConfigDefault
r1:
  planner_configs:
  - SBLkConfigDefault
  - ESTkConfigDefault
  - LBKPIECEkConfigDefault
  - BKPIECEkConfigDefault
  - KPIECEkConfigDefault
  - RRTkConfigDefault
  - RRTConnectkConfigDefault
  - RRTstarkConfigDefault
  - TRRTkConfigDefault
  - PRMkConfigDefault
  - PRMstarkConfigDefault
  - FMTkConfigDefault
  - BFMTkConfigDefault
  - PDSTkConfigDefault
  - STRIDEkConfigDefault
  - BiTRRTkConfigDefault
  - LBTRRTkConfigDefault
  - BiESTkConfigDefault
  - ProjESTkConfigDefault
  - LazyPRMkConfigDefault
  - LazyPRMstarkConfigDefault
  - SPARSkConfigDefault
  - SPARStwokConfigDefault
r2:
  planner_configs:
  - SBLkConfigDefault
  - ESTkConfigDefault
  - LBKPIECEkConfigDefault
  - BKPIECEkConfigDefault
  - KPIECEkConfigDefault
  - RRTkConfigDefault
  - RRTConnectkConfigDefault
  - RRTstarkConfigDefault
  - TRRTkConfigDefault
  - PRMkConfigDefault
  - PRMstarkConfigDefault
  - FMTkConfigDefault
  - BFMTkConfigDefault
  - PDSTkConfigDefault
  - STRIDEkConfigDefault
  - BiTRRTkConfigDefault
  - LBTRRTkConfigDefault
  - BiESTkConfigDefault
  - ProjESTkConfigDefault
  - LazyPRMkConfigDefault
  - LazyPRMstarkConfigDefault
  - SPARSkConfigDefault
  - SPARStwokConfigDefault
r3:
  planner_configs:
  - SBLkConfigDefault
  - ESTkConfigDefault
  - LBKPIECEkConfigDefault
  - BKPIECEkConfigDefault
  - KPIECEkConfigDefault
  - RRTkConfigDefault
  - RRTConnectkConfigDefault
  - RRTstarkConfigDefault
  - TRRTkConfigDefault
  - PRMkConfigDefault
  - PRMstarkConfigDefault
  - FMTkConfigDefault
  - BFMTkConfigDefault
  - PDSTkConfigDefault
  - STRIDEkConfigDefault
  - BiTRRTkConfigDefault
  - LBTRRTkConfigDefault
  - BiESTkConfigDefault
  - ProjESTkConfigDefault
  - LazyPRMkConfigDefault
  - LazyPRMstarkConfigDefault
  - SPARSkConfigDefault
  - SPARStwokConfigDefault
